spring:
  application:
    name: versioned-kv-store

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/kvstore}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  servlet:
    multipart:
      max-request-size: 1MB
      max-file-size: 1MB
    properties:
      hibernate:
        format_sql: true

        jdbc:
          batch_size: 50
          order_inserts: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always